### ISSUE TITLE
Multiple validators for an attribute

### ISSUE THREAD

**Issue by cbornet** [hynek/attrs#138] opened 2017-01-24 21:31 UTC
It would be very handy to be able to validate an attribute against a list of validators.
This way they can be composed easily
Eg :`validator: [instanceof(float), max(2), min(0)]`

**Comment by gvoysey** [comment] 2017-01-31 21:06
:+1: 

I was surprised this didn't "just work" when I tried it, honestly.

**Comment by hynek** [comment] 2017-02-04 09:59
this is a duplicate of #13.  we’re still trying to come up with something really good and lasting.  It seems like this road leads to re-implementing a validation framework which seems like a waste of time.

**Closed by hynek** 2017-02-04 09:59 UTC
Labels: duplicate

**Comment by cbornet** [comment] 2017-02-04 10:35
Yes, #13 looks similar. But a accepting a simple list of validators looks simpler to me

**Comment by hynek** [comment] 2017-02-04 13:40
You’re right, I’ve added it.  A bigger solution is coming but this can be achieved w/o external dependencies.

**Comment by cbornet** [comment] 2017-02-04 14:04
👍

**Comment by nicktimko** [comment] 2021-07-15 23:23
For those that get this via Googling: https://www.attrs.org/en/stable/api.html#attr.ib

**tl;dr**: passing a list of validators now works (since 17.1.0)
